### ISSUE TITLE
zattd command does not take --id flag as input!

### ISSUE THREAD

**Issue by gabbifish** [simonacca/zatt#1]
Hello there! I'm trying to use Zatt for a project and noticed that when running 
`zattd -c zatt.conf --id 0 -s zatt.0.persist --debug`
zattd throws an error that --id is an unrecognized argument. Turns out, "--id" is not even a flag recognized in server/config.py.

I'm currently looking into workarounds. One that didn't work was providing a node (from zatt.conf) IP addr and port in the --address and --port directories. I got the following error stacktrace for command `zattd -c zatt.conf --address "127.0.0.1" --port 5254 -s zatt.persist --debug`:

``` Traceback (most recent call last):
  File "/usr/local/bin/zattd", line 11, in <module>
    load_entry_point('Zatt==1.0', 'console_scripts', 'zattd')()
  File "/usr/local/lib/python3.6/site-packages/Zatt-1.0-py3.6.egg/zatt/server/main.py", line 31, in run
  File "/usr/local/lib/python3.6/site-packages/Zatt-1.0-py3.6.egg/zatt/server/main.py", line 10, in setup
  File "/usr/local/lib/python3.6/site-packages/Zatt-1.0-py3.6.egg/zatt/server/config.py", line 40, in __init__
  File "/usr/local/lib/python3.6/site-packages/Zatt-1.0-py3.6.egg/zatt/server/config.py", line 72, in _get
  File "/usr/local/lib/python3.6/site-packages/Zatt-1.0-py3.6.egg/zatt/server/config.py", line 72, in <setcomp>
ValueError: not enough values to unpack (expected 2, got 1) 
```

I'm going to look at the config.py file and see if there are any changes that could remedy this usage error. Wanted to give you a heads up in case you know anything about the problem.

**Comment by simonacca** [comment]
Hello and thanks for giving zatt a try!

I have not touched the project for a while, but I suspect that the `--id` CLI flag in the docs was referring to an earlier version of the software, apologies.

In any case, I have wanted to do some refactoring for a while now, I will look into this in the weekend if I manage, otherwise in the upcoming weeks, stay tuned!

**Comment by simonacca** [comment]
Alright,
by looking at the code I realized that ids are in fact not present anymore, a node is uniquely identified by the `(ip, port)` tuple. I will update the docs to reflect this.

**Comment by gabbifish** [comment]
Thanks!
